//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soulstice.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public string Description { get; set; }
        public int InstructorID { get; set; }
        public int ReservationLimit { get; set; }
        public decimal Fee { get; set; }
        public int WeekDayID { get; set; }
        public string Time { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual WeekDay WeekDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
